@url = http://localhost:8081
@cardId = af2488c7-1b1e-4c4b-a479-f377d3310ff4

### Create a new card
POST {{url}}/api/v1/cards
Content-Type: application/json

{
    "title": "Sample Card",
    "description": "1 This is a sample card description",
    "tags": [
    {
      "id": "550e8400-e29b-41d4-a716-446655440000"
    }
  ]
}

### Get all cards
GET {{url}}/api/v1/cards

### Get a card by id
GET {{url}}/api/v1/cards/{{cardId}}

### Update a card
PUT {{url}}/api/v1/cards/{{cardId}}
Content-Type: application/json

{
    "title": "Updated Test Card",
    "description": "This is an updated test card description",
    "tags": [
        {
            "id": "6adb4496-75f9-4c62-b8b6-076fd391aefd"
        },
        {
            "id": "2fd8361e-008b-4e65-90bd-0f139a3cdc11"
        }
    ]
}

### Delete a card
DELETE {{url}}/api/v1/cards/{{cardId}}

### Get random card
GET {{url}}/api/v1/cards/random/
