@url = http://localhost:8081
@cardId = 2d134b81-5556-41bc-8e19-29b1f8e41fd3

### Create a new card
POST {{url}}/api/v1/cards
Content-Type: application/json

{
    "title": "Sample Card",
    "description": "This is a sample card description",
    "tags": [
        {
            "id": "550e8400-e29b-41d4-a716-446655440000"
        }
    ]
}

### Get all cards
GET {{url}}/api/v1/cards

### Get a card by id
GET {{url}}/api/v1/cards/{{cardId}}

### Update a card
PUT {{url}}/api/v1/cards/{{cardId}}
Content-Type: application/json

{
    "title": "Updated Test Card",
    "description": "This is an updated test card description",
}

### Delete a card
DELETE {{url}}/api/v1/cards/{{cardId}}