@url = http://localhost:8081
@cardId = e6369048-7ff4-4e6e-9f3f-1f0447cdeb52

### Create a new card
POST {{url}}/api/v1/cards
Content-Type: application/json

{
    "title": "Sample Card",
    "description": "1 This is a sample card description",
    "tags": [
    {
      "id": "550e8400-e29b-41d4-a716-446655440000"
    }
  ]
}

### Get all cards
GET {{url}}/api/v1/cards

### Get a card by id
GET {{url}}/api/v1/cards/{{cardId}}

### Update a card
PUT {{url}}/api/v1/cards/{{cardId}}
Content-Type: application/json

{
    "title": "Updated Test Card",
    "description": "This is an updated test card description",
    "tags": [
    {
      "id": "7f581524-3f3f-4743-87dd-cc7c64e689d7"
    }
]
}

### Delete a card
DELETE {{url}}/api/v1/cards/{{cardId}}